config/routes.rb
PlatePal::Application.routes.draw do

  resources :coaches
  resources :patients do
    resources :goals
  end

  resources :photos do
    resources :comments
  end

  get "recent_comments" => "photos#recent_comments"

  
  resources :sessions
  resources :welcome

  root to: "welcome#show"

end

app/models/coach.rb
class Coach < ActiveRecord::Base
	has_secure_password

	has_many :patients
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :photo
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_secure_password

	has_many :photos
	has_many :goals
	belongs_to :coach
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :patient
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_patient
    @current_patient ||= Patient.find(session[:patient_id]) if session[:patient_id]
  end

  def current_coach
    @current_coach ||= Coach.find(session[:coach_id]) if session[:coach_id]
  end

  def calc_difference
    if current_patient.current_weeks_weight
	   current_patient.current_weeks_weight - current_patient.last_weeks_weight
   else
    return 0
   end
  end

  helper_method :current_patient
  helper_method :current_coach
  helper_method :calc_difference
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def new
  	@coach = Coach.new
  end

  def create
  	@coach = Coach.new(coach_params)
  	if @coach.save
      redirect_to root_path, notice: "Signed up!"
    else
      render :new
    end
  end

  def show
  	@coach = Coach.find(params[:id])
  end

  def edit
  	@coach = Coach.find(params[:id])
  end

  def update
  	@coach = Coach.find(params[:id])
  	if @coach.update_attributes(coach_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
  	@coach = Coach.find(params[:id])
    @coach.destroy
    redirect_to root_path
  end

  private
  def coach_params
  	params.require(:coach).permit(:name,:email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_photo

  def index
    @comments = Comment.all
  end

  def new
    @comment=Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.photo = @photo
    if current_patient
      @comment.name = current_patient.name
    elsif current_coach
      @comment.name = current_coach.name
    end
      @comment.photo_url = @photo.url
    if @comment.save
      redirect_to photo_path(@photo), notice: "Added new comment!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def load_photo
    @photo = Photo.find(params[:photo_id])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
  	@goals = Goal.all
  end

  def new
  	@goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to root_path, notice: "Goal Saved!"
    else
      render :new
    end
  end

  def show
  	@goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
  	@goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to root_path
  end

  private

  def goal_params
  	params.require(:goal).permit(:name, :description)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.coach = current_coach
    if @patient.save
      redirect_to root_path, notice: "New patient created!"
    else
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(patient_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to root_path
  end

  private
  def patient_params
    params.require(:patient).permit(:name,:email,:password,:password_confirmation, :age, :weight, :phone, :avatar, :current_weeks_weight, :last_weeks_weight, :height)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	
  def index
  	@photos = Photo.all
  end

  def new
  	@photo = Photo.new
  end

  def recent_comments
    @comments = Comment.last(5)
  end

  def create
  	@photo = Photo.new(photo_params)
  	@photo.patient = current_patient
    if @photo.save
      redirect_to root_path, notice: "Added new photo!"
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  	@photo = Photo.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_path
  end

  private
  def photo_params
    params.require(:photo).permit(:name,:url, :notes);
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	patient = Patient.find_by_email(params[:email])
    coach = Coach.find_by_email(params[:email])
  	if patient && patient.authenticate(params[:password])
  		session[:patient_id] = patient.id
  		redirect_to welcome_path(patient), notice: "Logged in!"
    elsif coach && coach.authenticate(params[:password])
      session[:coach_id] = coach.id
      redirect_to welcome_path(coach), notice: "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render :new
  	end
  end

  def new
  end

  def destroy
  	session.destroy
  	redirect_to new_session_path, notice: "Congrats, you've logged out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  	@photos = Photo.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.label :avatar %><br>
		<%= f.text_field :avatar %>
	</p>
	<p>
		<%= f.submit "Submit" %>
	</p>
<% end %>

app/views/coaches/edit.html.erb
<%= render "form" %>

app/views/coaches/new.html.erb
<%= render "form" %>

app/views/coaches/show.html.erb
<h1>Coaches#show</h1>
<p>Find me in app/views/coaches/show.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
  <section id="photo-comments">
   <div class="container">

     <div class="row recent-title">
      <div class="large-12 columns">
        <h2>recent activity</h2>
      </div>
    </div>

    <div class="row comments">
      <div class="small-3 columns">
        <img src="img/plate_pasta.jpg" class="comment-thumb">
      </div>

      <div class="small-9 columns" style="padding: 0">
        <div class="who-said-when">
          <p><strong>Bobby</strong> said today at 6:30pm</p>
        </div>
        <div class="said-what">
          <p>I'm trying a new soup today.</p>
        </div>
      </div>
    </div>

    <div class="row comments light">

      <div class="small-3 columns">
        <img src="img/mamas-food-square.jpg" class="comment-thumb">
      </div>

      <div class="small-9 columns" style="padding: 0">
        <div class="who-said-when">
          <p><strong>Barbara </strong>said today at 12:02pm</p>
        </div>
        <div class="said-what">
            <p>Yes, definitely looking more balanced, but you don't always need to fill your plate.</p>
        </div>
      </div>

    </div><!--comments row-->


    <div class="row comments">
      <div class="small-3 columns">
        <img src="img/mamas-food-square.jpg" class="comment-thumb">
      </div>

      <div class="small-9 columns" style="padding: 0">
        <div class="who-said-when">
          <p><strong>Bobby</strong> said today at 11:02am</p>
        </div>
        <div class="said-what">
          <p>Ok ok...is this better?</p>
        </div>
      </div>
    </div><!--comments row-->


    <div class="row comments light">
      <div class="small-3 columns">
        <img src="img/burger.jpg" class="comment-thumb">
      </div>

      <div class="small-9 columns" style="padding: 0">
        <div class="who-said-when">
          <p><strong>Barbara</strong> said yesterday at 10:00pm</p>
        </div>
        <div class="said-what">
          <p>Bobby...this will not get you any closer to your six-pack.</p>
        </div>
      </div>
    </div><!--comments row-->


  </div><!--container-->
</section><!--photo-large-->

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/goals/new.html.erb
<h1>Goals#new</h1>
<p>Find me in app/views/goals/new.html.erb</p>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.label :age %><br>
		<%= f.number_field :age %>
	</p>
	<p>
		<%= f.label :weight %><br>
		<%= f.number_field :weight %>
	</p>
	<p>
		<%= f.label :avatar %><br>
		<%= f.text_field :avatar %>
	</p>
	<p>
		<%= f.label :last_weeks_weight %><br>
		<%= f.number_field :last_weeks_weight, class: "text_field", step: "any" %>
	</p>
	<p>
		<%= f.label :current_weeks_weight %><br>
		<%= f.number_field :current_weeks_weight, class: "text_field", step: "any" %>
	</p>
	<p>
		<%= f.label :height %><br>
		<%= f.number_field :height, class: "text_field", step: "any" %>
	</p>
	<p>
		<%= f.submit "Submit" %>
	</p>
<% end %>

app/views/patients/index.html.erb
<% current_coach.patients.each do |patient| %>
	<%= link_to patient.name, edit_patient_path(patient) %><br>
	<%= link_to image_tag(patient.avatar), patient_path(patient) %>
<% end %>

app/views/patients/show.html.erb
<h1>Profile</h1>

Name: <%= @patient.name %><br>
Email: <%= @patient.email %><br>
Weight: <%= @patient.weight %><br>
Height: <%= @patient.height %><br>
Phone: <%= @patient.phone %><br>

<% @patient.photos.each do |photo| %>
	<%= photo.name %><br>
	<%= photo.notes %><br>
	<%= link_to image_tag("#{photo.url}"),photo_path(photo) %>
<% end %>

app/views/patients/update.html.erb
<h1>Patients#update</h1>
<p>Find me in app/views/patients/update.html.erb</p>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/edit.html.erb
<%= form_for [current_patient,@photo] do |f| %>
	<p>
		<%= label :name, 'Meal' %><br>
		<%= f.radio_button :name, 'Breakfast', :checked => true %> 
  		<%= label :name_breakfast, 'Breakfast' %><br>
  		<%= f.radio_button :name, 'Lunch' %>
  		<%= label :name_lunch, 'Lunch' %><br>
  		<%= f.radio_button :name, 'Dinner', :checked => true %> 
  		<%= label :name_dinner, 'Dinner' %><br>
  		<%= f.radio_button :name, 'Snack' %>
  		<%= label :name_snack, 'Snack' %><br>
	</p>
		<%= f.label :date %><br>
		<%= f.date_field :date %>
	</p>
	<p>
		<%= f.label :url %><br>
		<%= f.text_field :url %>
	</p>
	<p>
		<%= f.label :notes %><br>
		<%= f.text_field :notes %>
	</p>
	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>

app/views/photos/index.html.erb
<% if current_patient %>
	<% current_patient.photos.each do |f| %>
		<%= f.name %><br>
		<%= f.notes %><br>
		<%= link_to image_tag("#{f.url}"),photo_path(f) %>
	<% end %>
<% elsif current_coach %>

<% end %>

app/views/photos/new.html.erb
  <section id="photo-large">
    <div class="container">

      <div class="row">
        <div class="small-12 columns meal-img">
          <img src="img/mamas-food-square.jpg">
        </div>  
      </div>

    </div><!--container-->
  </section><!--photo-large-->

  <section id="photo-comments">
   <div class="container">

   	<%= form_for(@photo) do |f| %>

   		<!-- <div class="small-9 columns" style="padding: 0">
   		  <input type="radio"><label class="meal-type">Breakfast</label>
   		  <input type="radio"><label class="meal-type">Lunch</label>
   		  <input type="radio"><label class="meal-type">Dinner</label>
   		  <input type="radio"><label class="meal-type">Snack</label>
   		</div> -->


   		<div class="row comments">

   			<div class="small-3 columns" style="padding: 0">
   			  <label class="photo-deets">Meal</label>
   			</div>

   			<div class="small-9 columns" style="padding: 0">
		   		<p>
		   			<%= f.radio_button :name, 'Breakfast', :checked => true, class: "meal-type" %> 
		   	  		<%= label :name_breakfast, 'Breakfast',class: "meal-type" %>
		   	  		<%= f.radio_button :name, 'Lunch', class: "meal-type" %>
		   	  		<%= label :name_lunch, 'Lunch', class: "meal-type" %>
		   	  		<%= f.radio_button :name, 'Dinner', :checked => true, class: "meal-type" %> 
		   	  		<%= label :name_dinner, 'Dinner', class: "meal-type" %>
		   	  		<%= f.radio_button :name, 'Snack', class: "meal-type" %>
		   	  		<%= label :name_snack, 'Snack', class: "meal-type" %>
		   		</p>
	   		</div>
   		</div>

   		 <div class="row comments">

   		  <div class="small-3 columns" style="padding: 0">
   		    <label class="photo-deets">Date</label>
   		  </div>

   		  <div class="small-9 columns" style="padding: 0">
   		  	<p>
   		  		<%= f.date_field :date, id: "datepicker" %>
   		  	</p>
   		  </div>

   		</div>

   		 <div class="row comments">

   		  <div class="small-3 columns" style="padding: 0">
   		   <label class="photo-deets">URL</label>
   		  </div>

   		  <div class="small-9 columns" style="padding: 0">
   		  	<p>
   		  		<%= f.text_field :url, placeholder: "Enter the web address of the picture here." %>
   		  	</p>
   		  </div>

   		</div>

   		 <div class="row comments">

   		  <div class="small-3 columns" style="padding: 0">
   		   <label class="photo-deets">NOTES</label>
   		  </div>

   		  <div class="small-9 columns" style="padding: 0">
   		  	<p>
   		  		<%= f.text_field :notes, id: "notes", placeholder: "Make a note of what you ate..." %>
   		  	</p>
   		  </div>

   		</div>

   		<p>
   			<%= f.submit "Log it!", class: "button log-submit" %>
   		</p>
   	<% end %>

 </div><!--container-->
</section><!--photo-large-->


<input type="file" capture="camera" accept="image/*" id="takePictureField">
        
		<img id="yourimage">
 
		<div id="swatches">
			<div id="swatch0" class="swatch"></div>
			<div id="swatch1" class="swatch"></div>
			<div id="swatch2" class="swatch"></div>
			<div id="swatch3" class="swatch"></div>
			<div id="swatch4" class="swatch"></div>
		</div>

app/views/photos/recent_comments.html.erb
  <section id="photo-comments">
   <div class="container">

     <div class="row recent-title">
      <div class="large-12 columns">
        <h2>recent activity</h2>
      </div>
    </div>

    <% @comments.each do |f| %>
    	<!-- changing the colour of the comments box depending on who is making the comment -->
    	<% if f.name == current_patient.name %>
    		<div class="row comments">
    	<% else %>
    		<div class="row comments light">
    	<% end %>
    	  <div class="small-3 columns">
    	  	<%= link_to image_tag(f.photo_url, class: "comment-thumb"), photo_path(f.photo_id) %>
    	  </div>

    	  <div class="small-9 columns" style="padding: 0">
    	    <div class="who-said-when">
    	      <p><strong><%= f.name %></strong> said at <%= f.created_at %></p>
    	    </div>
    	    <div class="said-what">
    	      <p><%= f.content %></p>
    	    </div>
    	  </div>
    	</div>
    <% end %>

  </div><!--container-->
</section><!--photo-large-->

app/views/photos/show.html.erb
<p>
	<%= link_to "Edit", edit_photo_path(@photo) %>
</p>

<%= @photo.name %><br>
<%= @photo.notes %><br>
<%= image_tag("#{@photo.url}") %>

<%= form_for([@photo, @comment]) do |f| %>
  <p>
    <%= f.label :content, "Comment" %>
    <%= f.text_field :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<% @photo.comments.each do |f| %>
	<b>Name</b>: <%= f.name %>
	WHAT'd that boy say?<%= f.content %><br>
<% end %>

app/views/welcome/index.html.erb
<!-- Barbara was here -->

app/views/welcome/show.html.erb
<% if current_patient || current_coach %>

  <section id="prof-details">

    <div class="row prof-pic-details">

      <div class="small-4 columns prof-pic">
          <% if current_patient %>
            <%= link_to image_tag(current_patient.avatar), edit_patient_path(current_patient)  %>
          <% elsif current_coach %>
            <%= link_to image_tag(current_coach.avatar), edit_coach_path(current_coach)  %>
          <% end %>
      </div>

      <div class="small-5 columns prof-details">
        <% if current_patient %>
          <p>Name: <span class="user-attributes"><%= current_patient.name %></span></p>
          <p>Age: <span class="user-attributes"><%= current_patient.age %></span></p>
          <p>Current Weight: <span class="user-attributes"><%= current_patient.weight %>lbs</span></p>
          <p>Last Week's Weight: <span class="user-attributes"><%= current_patient.last_weeks_weight %>lbs</span></p>
          <p>Weight Change: 
            <% if (calc_difference > 0) %>
              <span class="user-attributes-gain"><%= calc_difference %>lbs</span>
            <% else %>
              <span class="user-attributes-loss"><%= calc_difference %>lbs</span>
            <% end %>
        <% elsif current_coach %>
          <p>Name: <span class="user-attributes"><%= current_coach.name %></span></p>
        <% end %>
          
      </div>

      <% if current_patient %>
      <div class="small-3 columns prof-progress">
        <p style="margin-bottom: 10px"><%= link_to "EDIT", edit_patient_path(current_patient)%></p>
        <p class="pounds">10 <span class="lbs">lbs</span></p>
      </div>

      <% end %>
    </div><!--end details row-->

    <div class="row" id="prof-buttons">
      <div class="small-6 columns">
        <% if current_patient %>
          <%= link_to "UPLOAD MEAL", new_photo_path, class: "button upload" %>
          <%= link_to "ALL MEALS", photos_path, class: "button upload" %>
        <% elsif current_coach %>
          <%= link_to "ADD PATIENT", new_patient_path, class: "button upload" %>
          <%= link_to "ALL PATIENTS", patients_path, class: "button upload" %>
        <% end %>
      </div>


      <div class="small-6 columns">
        <% if current_patient %>
          <%= link_to "GOALS", patient_goals_path(current_patient), class: "button upload" %>
          <%= link_to "RECENT FEEDBACK", recent_comments_path, class: "button comments-button" %>
        <% end %>
      </div>
    </div><!--end buttons row-->
  </section>


  <section id="prof-recent-photos">
    <div class="row prof-day-tab">
      <div class="small-1 columns">
        <h2 style="padding-top:5px;"> ◄ </h2>
      </div>
      <div class="small-10 columns">
        <h2>latest meals</h2>
      </div>
      <div class="small-1 columns">
        <h2 style="padding-top:5px;"> ► </h2>
      </div>
    </div><!--end recent photos-->


    <% if current_patient %>
    <ul class="small-block-grid-3">
    	<% current_patient.photos.each do |photo| %>
    		<li>
    			<%= link_to image_tag(photo.url, class: "th"), photo_path(photo) %>
    			<p class="meal"><%= photo.notes %></p>
    		</li>
    	<% end %>
    <% end %>
    </ul>

  </section>

<% end %>