config/routes.rb
PlatePal::Application.routes.draw do

  resources :coaches
  resources :patients do
    resources :goals
  end

  resources :photos do
    resources :comments
  end

  get "recent_comments" => "photos#recent_comments"

  
  resources :sessions
  resources :welcome

  root to: "welcome#show"

end

app/models/coach.rb
class Coach < ActiveRecord::Base
	has_secure_password

	has_many :patients
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :photo
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_secure_password

	has_many :photos
	has_many :goals
	belongs_to :coach
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :patient
	has_many :comments
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def new
  	@coach = Coach.new
  end

  def create
  	@coach = Coach.new(coach_params)
  	if @coach.save
      redirect_to root_path, notice: "Signed up!"
    else
      render :new
    end
  end

  def show
  	@coach = Coach.find(params[:id])
  end

  def edit
  	@coach = Coach.find(params[:id])
  end

  def update
  	@coach = Coach.find(params[:id])
  	if @coach.update_attributes(coach_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
  	@coach = Coach.find(params[:id])
    @coach.destroy
    redirect_to root_path
  end

  private
  def coach_params
  	params.require(:coach).permit(:name,:email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_photo

  def index
    @comments = Comment.all
  end

  def new
    @comment=Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.photo = @photo
    if current_patient
      @comment.name = current_patient.name
    elsif current_coach
      @comment.name = current_coach.name
    end
      @comment.photo_url = @photo.url
    if @comment.save
      redirect_to photo_path(@photo), notice: "Added new comment!"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def load_photo
    @photo = Photo.find(params[:photo_id])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
  	@goals = Goal.all
  end

  def new
  	@goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to root_path, notice: "Goal Saved!"
    else
      render :new
    end
  end

  def show
  	@goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
  	@goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to root_path
  end

  private

  def goal_params
  	params.require(:goal).permit(:name, :description)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.coach = current_coach
    if @patient.save
      redirect_to root_path, notice: "New patient created!"
    else
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(patient_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to root_path
  end

  private
  def patient_params
    params.require(:patient).permit(:name,:email,:password,:password_confirmation, :age, :weight, :phone, :avatar, :current_weeks_weight, :last_weeks_weight, :height)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	
  def index
  	@photos = Photo.all
  end

  def new
  	@photo = Photo.new
  end

  def recent_comments
    @comments = Comment.last(5)
  end

  def create
  	@photo = Photo.new(photo_params)
  	@photo.patient = current_patient
    if @photo.save
      redirect_to root_path, notice: "Added new photo!"
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  	@photo = Photo.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to root_path
  end

  private
  def photo_params
    params.require(:photo).permit(:name,:url, :notes);
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	patient = Patient.find_by_email(params[:email])
    coach = Coach.find_by_email(params[:email])
  	if patient && patient.authenticate(params[:password])
  		session[:patient_id] = patient.id
  		redirect_to welcome_path(patient), notice: "Logged in!"
    elsif coach && coach.authenticate(params[:password])
      session[:coach_id] = coach.id
      redirect_to welcome_path(coach), notice: "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render :new
  	end
  end

  def new
  end

  def destroy
  	session.destroy
  	redirect_to new_session_path, notice: "Congrats, you've logged out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  	@photos = Photo.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<?php require_once('../php/getusermedia.php');?>

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>

  <title>PlatePal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
  <script type="text/javascript" src="http://jqueryrotate.googlecode.com/svn/trunk/jQueryRotate.js"></script>

</head>
<body>
	<nav class="top-nav sticky" style="background-color: black;">
	  <ul class="small-block-grid-3 nav-icons">
	      <li>
	       
	      </li>
	      <li>
	        <%= link_to image_tag("logo.svg"),root_path, id: "nav_logo" %>
	      </li>
	      
	    </ul>    
	</nav>


	<script src="js/vendor/jquery.js"></script>
	<script src="js/foundation.min.js"></script>
	<script>
	  $(document).foundation();
	</script>

<%= yield %>

	<% if current_patient %>
		<%= link_to "EDIT PROFILE", edit_patient_path(current_patient) %>
		<%= link_to "LOG OUT", session_path("current"), method: :delete%>
	<% elsif current_coach %>
		<%= link_to "Sign up Patient", new_patient_path %><br>
		<%= link_to "EDIT PROFILE", edit_coach_path(current_coach) %>
		<%= link_to "LOG OUT", session_path("current"), method: :delete%>
		<br>
	<% else %>
		<%= link_to "Log in as Patient", new_session_path %> | 
		<%= link_to "Sign up as Practitioner", new_coach_path %> | 
		<%= link_to "Log in as Practitioner", new_session_path %>
	<% end %>


</body>
</html>